### ISSUE TITLE
Cannot use absolute paths

### ISSUE THREAD

**Issue by vimist** [vimist/watch-do#4]
When attempting to watch a file by its absolute path, a `NotImplementedError` is thrown. This can be seen when running the following command.

`watch-do -r -w /tmp/test -d 'echo %f has changed'`

The error:

```
Traceback (most recent call last):
  File "/usr/bin/watch-do", line 11, in <module>
    load_entry_point('watch-do==1.0.0', 'console_scripts', 'watch-do')()
  File "/usr/lib/python3.6/site-packages/watch_do/cli.py", line 203, in watch_do
    changed_files = watcher_manager.get_changed_files()
  File "/usr/lib/python3.6/site-packages/watch_do/watcher_manager.py", line 112, in get_changed_files
    new_files = self.glob_manager.get_files()
  File "/usr/lib/python3.6/site-packages/watch_do/glob_manager.py", line 61, in get_files
    for item in items:
  File "/usr/lib/python3.6/pathlib.py", line 1077, in glob
    raise NotImplementedError("Non-relative patterns are unsupported")
NotImplementedError: Non-relative patterns are unsupported
```

**Comment by vimist** [comment]
This has been fixed in 038f9a824acb96e2ac22bdfba64e8c1eaa7cdae0 v1.0.1
